kind: pipeline
name: drone-ecr-registry-plugin

workspace:
  base: /go
  path: src/github.com/davidbyttow/drone-ecr-registry-plugin

steps:
- name: test
  image: golang:latest
  environment:
  commands:
    - GO111MODULE=on go test -v ./...
  when:
    event:
      - push
      - pull_request

- name: build
  image: golang:latest
  commands:
    - make build
  when:
    event:
      - push
      - pull_request

- name: publish
  image: plugins/ecr
  settings:
    repo: 864091978270.dkr.ecr.ap-southeast-2.amazonaws.com/drone-ecr-registry-plugin:latest
    registry: 864091978270.dkr.ecr.ap-southeast-2.amazonaws.com/drone-ecr-registry-plugin:latest
    region: ap-southeast-2
    dockerfile: docker/Dockerfile
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
  when:
    event:
      - push
      - tag

#    branch:
#      - master
